### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by kochigami** [kochigami/aldebaran_robot_ws#59]
- [x] karuta demo modified 
- [ ] send a mail to friends about demo (asking for help) 
- [ ] send a mail to friends about experiment (asking for help) 
- [ ] do survey to university students (on January)
- [x] modify dialogue (12/30)
- [x] euslisp program modified (12/30)
- [ ] add robot movement
- [ ] add robot speech accent 
- [x] diary program modified (12/30)
- [ ] nao environment setup (on January)
- [ ] write my thetis!!!!!!!  (right now)

**Comment by kochigami** [comment]
maybe I should do nao environment setup on my desktop or use nao pc instead
